# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyledLink',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_styledlink_styledlink', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, default=b'', help_text='Required. The text that is linked.', max_length=255, verbose_name='link text')),
                ('title', models.CharField(blank=True, default=b'', help_text='Optional. If provided, will provide a tooltip for the link.', max_length=255, verbose_name='title')),
                ('int_destination_id', models.PositiveIntegerField(blank=True, null=True)),
                ('page_destination', models.CharField(blank=True, help_text='Use this to specify an intra-page link. Can be used for the <em>current page</em> or with a specific internal destination. Do <strong>not</strong> include a leading \u201c#\u201d.', max_length=64, verbose_name='intra-page destination')),
                ('int_hash', models.BooleanField(default=False)),
                ('ext_destination', models.TextField(blank=True, default=b'', verbose_name='external destination')),
                ('ext_follow', models.BooleanField(default=True, help_text='Let search engines follow this hyperlink?', verbose_name='follow external link?')),
                ('mailto', models.EmailField(blank=True, help_text='An email address. This will override an external url.', max_length=254, null=True, verbose_name='email address')),
                ('target', models.CharField(blank=True, choices=[(b'', 'same window'), (b'_blank', 'new window'), (b'_parent', 'parent window'), (b'_top', 'topmost frame')], default=b'', help_text='Optional. Specify if this link should open in a new tab or window.', max_length=100, verbose_name='target')),
                ('int_destination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='StyledLinkStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=b'', help_text='The internal name of this link style.', max_length=32, verbose_name='label')),
                ('link_class', models.CharField(default=b'', help_text='The class to add to this link (do NOT preceed with a ".").', max_length=32, verbose_name='link class')),
            ],
        ),
        migrations.AddField(
            model_name='styledlink',
            name='styles',
            field=models.ManyToManyField(blank=True, default=None, help_text='Optional. Choose one or more styles for this link.', related_name='styled_link_style', to='djangocms_styledlink.StyledLinkStyle', verbose_name='link style'),
        ),
    ]
